name: tf
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - _tflow_select=2.3.0
  - abseil-cpp=20211102.0
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - autopep8=1.6.0
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.5
  - colour=0.1.5
  - cryptography=38.0.1
  - cycler=0.11.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dtreeviz=1.4.1
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - expat=2.4.9
  - fftw=3.3.9
  - flatbuffers=2.0.0
  - flit-core=3.6.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.3.3
  - gast=0.5.3
  - getopt-win32=0.1
  - giflib=5.2.1
  - glib=2.69.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - graphviz=2.50.0
  - grpcio=1.42.0
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - gts=0.7.6
  - h5py=3.7.0
  - harfbuzz=4.3.0
  - hdf5=1.10.6
  - htmlmin=0.1.12
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - imagehash=4.3.1
  - imbalanced-learn=0.9.1
  - importlib-metadata=4.11.3
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter_client=7.4.7
  - jupyter_console=6.4.3
  - jupyter_core=4.11.2
  - jupyter_server=1.18.1
  - jupyterlab=3.5.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.16.3
  - jupyterlab_widgets=1.0.0
  - keras=2.9.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.2
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libcurl=7.86.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libgd=2.3.3
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxgboost=1.5.0
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lxml=4.9.1
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.1.1
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - multimethod=1.4
  - munkres=1.1.4
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.5.0
  - nest-asyncio=1.5.5
  - networkx=2.8.8
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numexpr=2.8.4
  - numpy=1.21.5
  - numpy-base=1.21.5
  - oauthlib=3.2.1
  - openssl=1.1.1s
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.5.1
  - pandas-profiling=3.5.0
  - pandocfilters=1.5.0
  - pango=1.50.7
  - parso=0.8.3
  - patsy=0.5.3
  - pcre=8.45
  - phik=0.12.2
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.38.0
  - pluggy=1.0.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - protobuf=3.20.1
  - psutil=5.9.0
  - pure_eval=0.2.2
  - py-xgboost=1.5.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11-abi=4
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pydantic=1.10.2
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytest=7.2.0
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=2.0
  - python-graphviz=0.20.1
  - python_abi=3.10
  - pytz=2022.1
  - pywavelets=1.3.0
  - pywin32=305
  - pywinpty=2.0.2
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.3.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.1.3
  - scipy=1.7.3
  - seaborn=0.12.1
  - seaborn-base=0.12.1
  - send2trash=1.8.0
  - setuptools=65.5.0
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - tangled-up-in-unicode=0.2.0
  - tensorboard=2.9.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.9.1
  - tensorflow-base=2.9.1
  - tensorflow-estimator=2.9.0
  - termcolor=2.1.0
  - terminado=0.13.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.1.1
  - typeguard=2.13.3
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022f
  - urllib3=1.26.12
  - vc=14.2
  - visions=0.7.5
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.0.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.14.1
  - xgboost=1.5.0
  - xz=5.2.8
  - yaml=0.2.5
  - yarl=1.8.1
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.13
  - zstd=1.5.2
